CREATE TABLE users (
    uid INT AUTO_INCREMENT PRIMARY KEY,
    id VARCHAR(30) NOT NULL UNIQUE,
    pw VARCHAR(255) NOT NULL,
    name VARCHAR(10) NOT NULL,
    email VARCHAR(50) NOT NULL UNIQUE,
    phone VARCHAR(20) NOT NULL UNIQUE,
    is_admin BOOLEAN DEFAULT 0
) DEFAULT CHARSET=utf8;


CREATE TABLE products (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    price DECIMAL(10) NOT NULL,
    category VARCHAR(100) DEFAULT NULL,
    description TEXT DEFAULT NULL
) DEFAULT CHARSET=utf8;

CREATE TABLE product_images (
    id INT AUTO_INCREMENT PRIMARY KEY,
    product_id INT NOT NULL,
    file_path VARCHAR(255) NOT NULL,
    img_url VARCHAR(255),
    is_thumbnail TINYINT(1) DEFAULT 0,
    FOREIGN KEY (product_id) REFERENCES products(id)
);